schema_version = "1.0.0"

id = "tracking_toolkit"
version = "3.0.0"
name = "Tracking Toolkit"
tagline = "Use OpenXR trackers and devices directly in Blender"
maintainer = "Ethan Porcaro <ethan@varrett.com>"
tags = ["Animation", "Tracking"]

type = "add-on"
blender_version_min = "5.3.0"
platforms = ["windows-x64", "linux-x64"]

license = [
    "SPDX:GPL-3.0-or-later",
]

wheels = []

[build]
paths_exclude_pattern = [
  "images/",  # Stuff for readme
  "__pycache__/",
  ".*",
  "*.zip",
  "DEVELOPMENT.md",
  "README.md",
  "requirements.txt",
  "requirements.dev.txt"
]

[permissions]
files = "Load custom shapes for tracker models"